
package Modulos.Venta;

//Librerias para conexion y modificar venta

import Modulos.*;
import Modulos.Conexion;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.util.ArrayList; //ArrayList
import javax.swing.JOptionPane;
import Clases.Venta;
import java.util.Arrays;
import java.util.List;
import static java.lang.System.exit;
import java.sql.CallableStatement;
import java.sql.ResultSet;
import java.sql.Statement;
import java.sql.Types;

public class Modificar_Venta extends javax.swing.JFrame {

    Venta sell;
    public Modificar_Venta(Venta sell) {
        this.sell=sell; //Al se crearse la ventana se asocia el venta a modificar en el atributo
        initComponents();
        Originales();
        //Conexion db= new Conexion();
        //database=db.getConnection();
        getVenta(); //Obtiene los datos del objeto venta para colocarlo en los TXT editables
    }

    //Atributos de conexion
    //Conexion db;
    //Connection database;
    String[] Productos;
    int[] Precios=null;
    int[] Cantidades;
    int[] Cantidades_Originales;
    
    private void Originales(){
        
        List <String> mount= Arrays.asList(sell.getCantidades().split(","));
        List <String> products= Arrays.asList(sell.getProductos().split(","));
        Cantidades= new int[mount.size()];
        Cantidades_Originales= new int[mount.size()];
        Productos= new String[products.size()];
        int i=0;
        for (String item:mount) {
            Cantidades[i]=Integer.parseInt(item);
            Cantidades_Originales[i]=Integer.parseInt(item);
            i++;
        }
        i=0;
        for (String item:products) {
            Productos[i]=item;
            i++;
        }
        
    }
     public void setMonto(){
        int monto=0;
        for (int num:Precios) {
            monto+=num;
        }
        TXT_MONTO.setText(String.valueOf(monto));
    }
    public void getVenta(){ //Metodo para rellenar los TXT con los datos del objeto venta obtenido al buscarlo
        List <String> products= Arrays.asList(sell.getProductos().split(","));
        try{
            TXT_ID.setText(sell.getID());
            TXT_MONTO.setText(sell.getMonto());
            for (String f:products) {
                PRODUCTOS.add(f);
            }
            if (sell.getPago().equals("Efectivo")) {
                COMBO_PAGO.setSelectedIndex(0);
            }
            else if (sell.getPago().equals("Tarjeta")) {
                COMBO_PAGO.setSelectedIndex(1);
            }
            else if (sell.getPago().equals("SINPE")) {
                COMBO_PAGO.setSelectedIndex(2);
            }
            else{
                
            }
            
            TXT_COMPRADOR.setText(sell.getComprador());
            TXT_VENDEDOR.setText(sell.getVendedor());
            TXT_FECHA.setText(sell.getFecha());
        }
        catch(Exception ex){
        JOptionPane.showMessageDialog(null, ex);
    }
        
    }
    int Inventario[];
     private boolean Validar(){
        int i=0;
        boolean val=false;
        Inventario=new int[Productos.length];
        for (String item:Productos) {
            try{
                CallableStatement buscar = General.database.prepareCall("{call OBTENER_CANTIDADES_PRODUCTOS(?,?)}");
                buscar.setInt(1, Integer.parseInt(item));
                buscar.registerOutParameter(2, Types.REF_CURSOR);
                buscar.execute();
                ResultSet rs=(ResultSet)buscar.getObject(2);
                rs.next();
                int cant=rs.getInt(1);
                Inventario[i]=cant;
                if(cant+Cantidades_Originales[i]>=Cantidades[i]){
                    val=true;
                }
                else{
                    return false;
                }
            }
            catch(Exception ex){
                return false;
            }
            i++;
        }
        return val;
     }
     
     private void ActualizarInventario(){
         int finales;
         int i=0;
         for (int num:Cantidades_Originales) {
             finales=num-Cantidades[i];
             System.out.println(Cantidades[i]);
             System.out.println(Cantidades_Originales[i]);
             System.out.println(finales);
             try{
                 int n=Inventario[i]+finales;
                 PreparedStatement modificar = General.database.prepareStatement("UPDATE productos SET cantidad='"+n+"' WHERE codigo='"+Productos[i]+"'");
                 modificar.executeUpdate();
                 modificar.close();
             }
             catch(Exception ex){
                 System.out.println(ex);
             }
             
             i++;
         }
         
     }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        DESHACER = new javax.swing.JButton();
        MODIFICAR = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        TXT_MONTO = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        PRODUCTOS = new java.awt.List();
        jLabel2 = new javax.swing.JLabel();
        COMBO_PAGO = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        TXT_COMPRADOR = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        TXT_VENDEDOR = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        TXT_FECHA = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        TXT_ID = new javax.swing.JTextField();
        CANTIDADES = new javax.swing.JButton();
        NombreDeTienda = new javax.swing.JLabel();
        BACK = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        EXIT = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setUndecorated(true);
        setSize(new java.awt.Dimension(1124, 749));

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));
        jPanel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel1MouseClicked(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(204, 255, 0));

        DESHACER.setBackground(new java.awt.Color(255, 255, 204));
        DESHACER.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        DESHACER.setText("Deshacer");
        DESHACER.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                DESHACERMouseClicked(evt);
            }
        });
        DESHACER.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DESHACERActionPerformed(evt);
            }
        });

        MODIFICAR.setBackground(new java.awt.Color(255, 255, 204));
        MODIFICAR.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        MODIFICAR.setText("Modificar");
        MODIFICAR.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                MODIFICARMouseClicked(evt);
            }
        });
        MODIFICAR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MODIFICARActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 204));
        jLabel1.setText("Monto");

        TXT_MONTO.setEditable(false);
        TXT_MONTO.setEnabled(false);

        jLabel8.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 204));
        jLabel8.setText("Productos");

        PRODUCTOS.setEnabled(false);

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 204));
        jLabel2.setText("Método de Pago");

        COMBO_PAGO.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Efectivo", "Tarjeta", "SINPE" }));
        COMBO_PAGO.setToolTipText("");

        jLabel4.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 204));
        jLabel4.setText("Cédula del Comprador");

        TXT_COMPRADOR.setEditable(false);
        TXT_COMPRADOR.setEnabled(false);

        jLabel6.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 204));
        jLabel6.setText("Cédula del Vendedor");

        TXT_VENDEDOR.setEditable(false);
        TXT_VENDEDOR.setEnabled(false);

        jLabel5.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 204));
        jLabel5.setText("Fecha(dd/mm/aaaa)");

        TXT_FECHA.setEditable(false);
        TXT_FECHA.setEnabled(false);

        jLabel9.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 204));
        jLabel9.setText("ID");

        TXT_ID.setEnabled(false);

        CANTIDADES.setBackground(new java.awt.Color(255, 255, 204));
        CANTIDADES.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        CANTIDADES.setText("Definir Cantidades");
        CANTIDADES.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                CANTIDADESMouseClicked(evt);
            }
        });

        NombreDeTienda.setBackground(new java.awt.Color(255, 255, 255));
        NombreDeTienda.setFont(new java.awt.Font("Edwardian Script ITC", 1, 60)); // NOI18N
        NombreDeTienda.setForeground(new java.awt.Color(255, 255, 255));
        NombreDeTienda.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        NombreDeTienda.setText("Tienda La Moda");

        BACK.setFont(new java.awt.Font("Bell MT", 0, 40)); // NOI18N
        BACK.setForeground(new java.awt.Color(255, 255, 153));
        BACK.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        BACK.setText("«");
        BACK.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        BACK.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BACKMouseClicked(evt);
            }
        });

        jLabel12.setFont(new java.awt.Font("Bell MT", 1, 28)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 153));
        jLabel12.setText("VENTAS");

        EXIT.setFont(new java.awt.Font("Bell MT", 0, 24)); // NOI18N
        EXIT.setForeground(new java.awt.Color(255, 255, 153));
        EXIT.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        EXIT.setText("X");
        EXIT.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        EXIT.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                EXITMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(BACK)
                .addGap(14, 14, 14)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel9))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(TXT_ID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel3))
                            .addComponent(TXT_MONTO, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(EXIT))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(30, 30, 30)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                                    .addComponent(NombreDeTienda)
                                    .addComponent(jLabel12))
                                .addGap(212, 212, 212))))
                    .addComponent(jLabel8)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(18, 18, 18)
                        .addComponent(COMBO_PAGO, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel6)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(TXT_COMPRADOR, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(TXT_VENDEDOR, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(TXT_FECHA, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                            .addComponent(DESHACER)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(MODIFICAR))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                            .addComponent(PRODUCTOS, javax.swing.GroupLayout.PREFERRED_SIZE, 224, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(CANTIDADES))))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(74, 74, 74)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel9)
                                .addComponent(TXT_ID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(23, 23, 23)
                                        .addComponent(jLabel8)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(PRODUCTOS, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(76, 76, 76)
                                        .addComponent(CANTIDADES))))
                            .addComponent(TXT_MONTO, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(NombreDeTienda)
                            .addComponent(EXIT))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel12))
                    .addComponent(BACK))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(COMBO_PAGO, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(TXT_COMPRADOR, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(TXT_VENDEDOR, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(TXT_FECHA, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(DESHACER)
                    .addComponent(MODIFICAR))
                .addContainerGap(163, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void DESHACERActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DESHACERActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_DESHACERActionPerformed

    private void jPanel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel1MouseClicked
       
    }//GEN-LAST:event_jPanel1MouseClicked

    private void MODIFICARMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MODIFICARMouseClicked
        if (Validar()) {
             //Array list para facilitar a la hora de escribir la sentebcia SQL
        ArrayList<String> venta = new ArrayList();
       
      venta.add(TXT_MONTO.getText());
      String productos="";
           String[] lista = PRODUCTOS.getItems();
           for (String i:lista) {
                productos+=i+",";
            
           }
      venta.add(productos);
      venta.add(COMBO_PAGO.getSelectedItem().toString());
      venta.add(TXT_COMPRADOR.getText());
      venta.add(TXT_VENDEDOR.getText());
      venta.add(TXT_FECHA.getText());
      String cantidades="";
           for (int i:Cantidades) {
                cantidades+=String.valueOf(i)+",";
            
           }
      venta.add(cantidades);
        try{
            CallableStatement modificar= General.database.prepareCall("{call ACTUALIZAR_VENTA(" + Integer.parseInt(sell.getID()) + "," + Integer.parseInt(venta.get(0)) + ",'" + venta.get(1) + "','" + venta.get(2) + "'," + Integer.parseInt(venta.get(3)) + "," + Integer.parseInt(venta.get(3)) + ",'" +venta.get(6)+ "')}");
            //Se prepara sentencia SQL
           
           //Se ejecuta el SQL
           modificar.executeUpdate();
           modificar.close();
           ActualizarInventario();
           JOptionPane.showMessageDialog(null, "Venta modificada con exito");
          //Se devuelve a la ventana de busqueda
          Ventas ventana = new Ventas();
           ventana.setVisible(true);
           this.setVisible(false);
           
       }
       catch(Exception EX){
           System.out.println("ERROR AL MODIFICAR "+EX);
       }
        }
       
    }//GEN-LAST:event_MODIFICARMouseClicked

    private void DESHACERMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_DESHACERMouseClicked
        getVenta();
    }//GEN-LAST:event_DESHACERMouseClicked

    private void MODIFICARActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MODIFICARActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_MODIFICARActionPerformed

    private void CANTIDADESMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CANTIDADESMouseClicked

        if (Productos!=null) {
            Carrito ventana = new Carrito(this);
            ventana.setVisible(true);
        }
    }//GEN-LAST:event_CANTIDADESMouseClicked

    private void BACKMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BACKMouseClicked
        Ventas ventana = new Ventas();
        ventana.setLocationRelativeTo(null);
        ventana.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_BACKMouseClicked

    private void EXITMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_EXITMouseClicked
        exit(0);
    }//GEN-LAST:event_EXITMouseClicked

    /**
     * @param args the command line arguments
     */
   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel BACK;
    private javax.swing.JButton CANTIDADES;
    private javax.swing.JComboBox<String> COMBO_PAGO;
    private javax.swing.JButton DESHACER;
    private javax.swing.JLabel EXIT;
    private javax.swing.JButton MODIFICAR;
    private javax.swing.JLabel NombreDeTienda;
    private java.awt.List PRODUCTOS;
    private javax.swing.JTextField TXT_COMPRADOR;
    private javax.swing.JTextField TXT_FECHA;
    private javax.swing.JTextField TXT_ID;
    private javax.swing.JTextField TXT_MONTO;
    private javax.swing.JTextField TXT_VENDEDOR;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
